### ISSUE TITLE
Page image assets load slowly

### ISSUE THREAD

**Issue by deansheather** [ClubWumpus/Minigames-Menu#5]
An effort should be made to make the image assets smaller, as they take a while to load over a slower connection.
- The background can be made to tile and also compressed into a jpg
- The game images can be compressed into a jpg

**Comment by Stoupedog** [comment]
Images from `clubwump.us`, `play.clubwump.us` and `flappy.clubwump.us` should now be compressed 👍  (https://github.com/ClubWumpus/Minigames-Menu/pull/6/commits/76a77edebfa9e6a20d6527f7ce668c71fbe5a872 , https://github.com/ClubWumpus/web/pull/57/commits/392a0c7b2fe9757b1aaea92eaa04fff88ba41dad and https://github.com/ClubWumpus/Flappy-Wumpus/pull/150/commits/fe3c55b2a97143745823e8ad78ee97b76e8150da)
